routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('clientes', 'App\Http\Controllers\ClienteController')->middleware('auth');
Route::resource('produtos', 'App\Http\Controllers\ProdutoController')->middleware('auth');
Route::resource('pedidos', 'App\Http\Controllers\PedidoController')->middleware('auth');

app/Models/Produto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    use HasFactory;
    protected $table = 'produtos';
    protected $fillable = ['nome_produto', 'valor_unitario', 'cod_barras'];
}

app/Http/Controllers/ProdutoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produto;
use Illuminate\Http\Request;

class ProdutoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produtos = Produto::all();
        return view('produto.index', ['titulo' => 'Produtos', 'produtos' => $produtos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('produto.create', ['titulo' => 'Cadastrar Produto']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'nome_produto' => 'required|min:3|max:100',
                'valor_unitario' => 'required',
                'cod_barras' => 'required|max:20'
            ],
            [
                'required' => 'Campo :attribute é obrigatório seu preenchimento',
                'nome_produto.min' => 'O nome do produto deve ter no mínimo 3 caracteres',
                'nome_produto.max' => 'O nome do produto deve ter no máximo 100 caracteres',
                'cod_barras.max' => 'O cod de barras deve ter no máximo 20 caracteres'
            ]
        );

        Produto::create($request->all());
        return back()->with('success', 'Produto ' . $request->input('nome_produto') . ' cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Produto  $produto
     * @return \Illuminate\Http\Response
     */
    public function show(Produto $produto)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Produto  $produto
     * @return \Illuminate\Http\Response
     */
    public function edit(Produto $produto)
    {
        return view('produto.edit', ['titulo' => "Editar Produto", 'produto' => $produto]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Produto  $produto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Produto $produto)
    {
        $request->validate(
            [
                'nome_produto' => 'required|min:3|max:100',
                'valor_unitario' => 'required',
                'cod_barras' => 'required|max:20'
            ],
            [
                'required' => 'Campo :attribute é obrigatório seu preenchimento',
                'nome_produto.min' => 'O nome do produto deve ter no mínimo 3 caracteres',
                'nome_produto.max' => 'O nome do produto deve ter no máximo 100 caracteres',
                'cod_barras.max' => 'O cod de barras deve ter no máximo 20 caracteres'
            ]
        );

        $produto->update($request->all());
        return back()->with('success', 'Produto ' . $request->input('nome_produto') . ' editado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Produto  $produto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Produto $produto)
    {
        $produto->delete();
        return back()->with('success', 'Produto deletado com sucesso!');
    }
}

resources/views/produto/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{$titulo}}</h1>
    <div class="row justify-content-center">
        <div class="col-6" style="margin:auto;">
            @if ($errors->any())
              <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
                @foreach ($errors->all() as $erro)
                  <p>{{ $erro }}</p>
                @endforeach
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            @endif
            @if (session()->has('success'))
              <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
                {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            @endif
            @component('produto.form_create_edit')
            @endcomponent
        </div>
    </div>
</div>
@endsection

resources/views/produto/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{$titulo}}</h1>
    <div class="row justify-content-center">
        <div class="col-6" style="margin:auto;">
            @if ($errors->any())
              <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
                @foreach ($errors->all() as $erro)
                  <p>{{ $erro }}</p>
                @endforeach
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            @endif
            @if (session()->has('success'))
              <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
                {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            @endif
            @component('produto.form_create_edit', ['produto' => $produto])
            @endcomponent
        </div>
    </div>
</div>
@endsection

resources/views/produto/form_create_edit.blade.php
@if (isset($produto->id))
<form method="post" class action="{{ route('produtos.update', $produto['id']) }}">
    @csrf
    @method('PUT')
    <input type="hidden" name="produto_id" value="{{$produto->id}}" />
@else
<form method="post" action="{{ route('produtos.store') }}">
    @csrf
@endif
    <div class="form-group mb-3">
        <input type="text" class="form-control" value="{{ $produto->nome_produto ?? old('nome_produto') }}" id="nome_produto" name="nome_produto"
        placeholder="Nome do Produto">
    </div>
    <div class="form-group mb-3">
        <input type="text" class="form-control" value="{{ $produto->valor_unitario ?? old('valor_unitario') }}" id="valor_unitario" name="valor_unitario"
        placeholder="Valor unitário">
    </div>
    <div class="form-group mb-3">
        <input type="number" class="form-control" value="{{ $produto->cod_barras ?? old('cod_barras') }}" id="cod_barras" name="cod_barras"
        placeholder="Cod barras">
    </div>
    <div class="form-group mt-3">
        <button type="submit" class="btn btn-primary">@if (isset($produto->id)) Editar @else Cadastrar @endif Produto </button>
    </div>
</form>

resources/views/produto/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{$titulo}}</h1>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="col">
                <div class="mt-10">
                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
                        @foreach ($errors->all() as $erro)
                            <p>{{ $erro }}</p>
                        @endforeach
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    @if (session()->has('success'))
                        <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
                        {{ session('success') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    <table class="table table-sm table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">PRODUTO</th>
                                <th scope="col">VALOR UNITÁRIO</th>
                                <th scope="col">COD BARRAS</th>
                                <th scope="col">DATA DE CRIAÇÃO</th>
                                <th scope="col">DATA DE ATUALIZAÇÃO</th>
                                <th scope="col">
                                    <div class="form-group">
                                        <a href="{{route('produtos.create')}}" class="btn btn-primary btn-sm">Cadastrar Produto</a>
                                    </div>
                                </th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($produtos as $produto)
                                <tr>
                                    <th scope="row">{{$produto['id']}}</th>
                                    <td>{{$produto['nome_produto']}}</td>
                                    <td>{{$produto['valor_unitario']}}</td>
                                    <td>{{$produto['cod_barras']}}</td>
                                    <td>{{date('d/m/Y h:m:s', strtotime($produto['created_at']))}}</td>
                                    <td>{{date('d/m/Y h:m:s', strtotime($produto['updated_at']))}}</td>
                                    <td><a href="{{route('produtos.edit', $produto['id'])}}" class="btn btn-warning btn-sm">Editar Produto</a></td>
                                    <td>
                                        <button type="button" class="btn btn-danger btn-sm deletar" data-toggle="modal" data-id="{{$produto['id']}}" data-name="{{$produto['nome_produto']}}" data-target="#modalDeletar">
                                            Deletar Produto
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalDeletar" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h5 class="modal-title link-light" id="TituloModalCentralizado">Deletar Produto</h5>
                    <button type="button btn-dark" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Tem certeza que você deseja deletar o Produto <b></b>?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary close" data-dismiss="modal">Cancelar</button>
                    <form method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Deletar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('.deletar, .close').click(function () {
                $('#modalDeletar').modal('toggle');
                $('.modal-body b').html($(this).attr("data-name"));
                $('.modal-footer form').attr("action", "/produtos/" + $(this).attr("data-id") + "");
            });
        });
    </script>
</div>
@endsection