routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('clientes', 'App\Http\Controllers\ClienteController')->middleware('auth');
Route::resource('produtos', 'App\Http\Controllers\ProdutoController')->middleware('auth');
Route::resource('pedidos', 'App\Http\Controllers\PedidoController')->middleware('auth');

app/Models/Pedido.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pedido extends Model
{
    use HasFactory;
    protected $table = 'pedidos';
    protected $fillable = ['cliente_id', 'produto_id', 'status', 'quantidade'];
}

app/Http/Controllers/PedidoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cliente;
use App\Models\Pedido;
use App\Models\Produto;
use Illuminate\Http\Request;

class PedidoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pedidos = Pedido::all();
        return view('pedido.index', ['titulo' => 'Pedidos', 'pedidos' => $pedidos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clientes = Cliente::all();
        $produtos = Produto::all();
        return view('pedido.create', ['titulo' => 'Cadastrar Pedido', 'clientes' => $clientes, 'produtos' => $produtos]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'cliente_id' => 'required',
                'produto_id' => 'required',
                'status' => 'required',
                'quantidade' => 'required|max:11'
            ],
            [
                'required' => 'Campo :attribute é obrigatório seu preenchimento',
                'quantidade.max' => 'A quantidade deve ter no máximo 11 caracteres'
            ]
        );

        Pedido::create($request->all());
        return back()->with('success', 'Pedido ' . $request->input('id') . ' cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pedido  $pedido
     * @return \Illuminate\Http\Response
     */
    public function show(Pedido $pedido)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pedido  $pedido
     * @return \Illuminate\Http\Response
     */
    public function edit(Pedido $pedido)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pedido  $pedido
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pedido $pedido)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pedido  $pedido
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pedido $pedido)
    {
        $pedido->delete();
        return back()->with('success', 'Pedido deletado com sucesso!');
    }
}

resources/views/pedido/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{ $titulo }}</h1>
  <div class="row">
    <div class="col-6" style="margin:auto;">
        @if ($errors->any())
            <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
            @foreach ($errors->all() as $erro)
                <p>{{ $erro }}</p>
            @endforeach
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @if (session()->has('success'))
            <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @component('pedido.form_create_edit', ['clientes' => $clientes, 'produtos' => $produtos])
        @endcomponent
    </div>
</div>
@endsection

resources/views/pedido/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{ $titulo }}</h1>
  <div class="row">
    <div class="col-6" style="margin:auto;">
        @if ($errors->any())
            <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
            @foreach ($errors->all() as $erro)
                <p>{{ $erro }}</p>
            @endforeach
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @if (session()->has('success'))
            <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @component('pedido.form_create_edit', ['clientes' => $clientes, 'produtos' => $produtos])
        @endcomponent
    </div>
</div>
@endsection

resources/views/pedido/form_create_edit.blade.php
<form method="post" action="{{ route('pedidos.store') }}">
    @csrf
    <div class="form-group mb-3">
        <select class="form-control" name="cliente_id" id="cliente_id">
            <option value="">Escolha o cliente</option>
            @foreach ($clientes as $cliente)
                <option value="{{$cliente['id']}}" {{ ($pedido->cliente_id ?? old('cliente_id')) == $cliente['id'] ? 'selected' : '' }}>{{$cliente['nome_cliente']}}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group mb-3">
        <select class="form-control" name="produto_id" id="produto_id">
            <option value="">Escolha o produto</option>
            @foreach ($produtos as $produto)
                <option value="{{$produto['id']}}" {{ ($pedido->produto_id ?? old('produto_id')) == $produto['id'] ? 'selected' : '' }}>{{$produto['nome_produto']}}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group mb-3">
        <select class="form-control" name="status" id="status">
            <option value="">Escolha o status</option>
            <option value="Em Aberto" {{ ($pedido->status ?? old('status')) == "Em Aberto" ? 'selected' : '' }}>Em Aberto</option>
            <option value="Pago" {{ ($pedido->status ?? old('status')) == "Pago" ? 'selected' : '' }}>Pago</option>
            <option value="Cancelado" {{ ($pedido->status ?? old('status')) == "Cancelado" ? 'selected' : '' }}>Cancelado</option>
        </select>
    </div>
    <div class="form-group mb-3">
        <input type="number" class="form-control" value="{{ $pedido->quantidade ?? old('quantidade') }}" id="quantidade" name="quantidade"
        placeholder="Quantidade">
    </div>
    <div class="form-group mt-3">
        <button type="submit" class="btn btn-primary">Cadastrar Pedido </button>
    </div>
</form>

resources/views/pedido/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{$titulo}}</h1>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="col">
                <div class="mt-10">
                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
                        @foreach ($errors->all() as $erro)
                            <p>{{ $erro }}</p>
                        @endforeach
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    @if (session()->has('success'))
                        <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
                        {{ session('success') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    <table class="table table-sm table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">ID PEDIDO</th>
                                <th scope="col">ID CLIENTE</th>
                                <th scope="col">ID PRODUTO</th>
                                <th scope="col">STATUS</th>
                                <th scope="col">QTD</th>
                                <th scope="col">DATA DE CRIAÇÃO</th>
                                <th scope="col">DATA DE ATUALIZAÇÃO</th>
                                <th scope="col">
                                    <div class="form-group">
                                        <a href="{{route('pedidos.create')}}" class="btn btn-primary btn-sm">Cadastrar Pedido</a>
                                    </div>
                                </th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($pedidos as $pedido)
                                <tr>
                                    <th scope="row">{{$pedido['id']}}</th>
                                    <td><a href="{{route('clientes.edit', $pedido['cliente_id'])}}" target="_blank">{{$pedido['cliente_id']}}</a></td>
                                    <td><a href="{{route('produtos.edit', $pedido['produto_id'])}}" target="_blank">{{$pedido['produto_id']}}</a></td>
                                    <td>{{$pedido['status']}}</td>
                                    <td>{{$pedido['quantidade']}}</td>
                                    <td>{{date('d/m/Y h:m:s', strtotime($pedido['created_at']))}}</td>
                                    <td>{{date('d/m/Y h:m:s', strtotime($pedido['updated_at']))}}</td>
                                    <td>
                                        <button type="button" class="btn btn-danger btn-sm deletar" data-toggle="modal" data-id="{{$pedido['id']}}" data-name="{{$pedido['id']}}" data-target="#modalDeletar">
                                            Deletar Pedido
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalDeletar" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h5 class="modal-title link-light" id="TituloModalCentralizado">Deletar Pedido</h5>
                    <button type="button btn-dark" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Tem certeza que você deseja deletar o Pedido <b></b>?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary close" data-dismiss="modal">Cancelar</button>
                    <form method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Deletar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('.deletar, .close').click(function () {
                $('#modalDeletar').modal('toggle');
                $('.modal-body b').html($(this).attr("data-name"));
                $('.modal-footer form').attr("action", "/pedidos/" + $(this).attr("data-id") + "");
            });
        });
    </script>
</div>
@endsection