routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('clientes', 'App\Http\Controllers\ClienteController')->middleware('auth');
Route::resource('produtos', 'App\Http\Controllers\ProdutoController')->middleware('auth');
Route::resource('pedidos', 'App\Http\Controllers\PedidoController')->middleware('auth');

app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    use HasFactory;
    protected $table = 'clientes';
    protected $fillable = ['nome_cliente', 'email', 'cpf'];
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cliente;
use Illuminate\Http\Request;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clientes = Cliente::all();
        return view('cliente.index', ['titulo' => 'Clientes', 'clientes' => $clientes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cliente.create', ['titulo' => 'Cadastrar Cliente']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'nome_cliente' => 'required|min:3|max:100',
                'email' => 'email|max:50',
                'cpf' => 'required|max:11'
            ],
            [
                'required' => 'Campo :attribute é obrigatório seu preenchimento',
                'nome_cliente.min' => 'O nome do cliente deve ter no mínimo 3 caracteres',
                'nome_cliente.max' => 'O nome do cliente deve ter no máximo 100 caracteres',
                'email.max' => 'Campo e-mail é permitido até 50 caracteres',
                'email.unique' => 'E-mail já cadastrado, por favor digite outro e-mail.'
            ]
        );

        Cliente::create($request->all());
        return back()->with('success', 'Cliente ' . $request->input('nome_cliente') . ' cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function show(Cliente $cliente)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function edit(Cliente $cliente)
    {
        //$cliente = Cliente::all();
        return view('cliente.edit', ['titulo' => "Editar Cliente", 'cliente' => $cliente]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cliente $cliente)
    {
        $request->validate(
            [
                'nome_cliente' => 'required|min:3|max:100',
                'email' => 'email|max:50',
                'cpf' => 'required|max:11'
            ],
            [
                'required' => 'Campo :attribute é obrigatório seu preenchimento',
                'nome_cliente.min' => 'O nome deve ter no mínimo 3 caracteres',
                'nome_cliente.max' => 'O nome deve ter no máximo 50 caracteres',
                'email.max' => 'Campo e-mail é permitido até 100 caracteres',
                'email.unique' => 'E-mail já cadastrado, por favor digite outro e-mail.'
            ]
        );

        $cliente->update($request->all());
        return back()->with('success', 'Cliente ' . $request->input('nome_cliente') . ' editado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cliente $cliente)
    {
        $cliente->delete();
        return back()->with('success', 'Cliente deletado com sucesso!');
    }
}

resources/views/cliente/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{$titulo}}</h1>
    <div class="row justify-content-center">
        <div class="col-6" style="margin:auto;">
            @if ($errors->any())
              <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
                @foreach ($errors->all() as $erro)
                  <p>{{ $erro }}</p>
                @endforeach
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            @endif
            @if (session()->has('success'))
              <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
                {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            @endif
            @component('cliente.form_create_edit')
            @endcomponent
        </div>
    </div>
</div>
@endsection

resources/views/cliente/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{$titulo}}</h1>
    <div class="row justify-content-center">
        <div class="col-6" style="margin:auto;">
            @if ($errors->any())
              <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
                @foreach ($errors->all() as $erro)
                  <p>{{ $erro }}</p>
                @endforeach
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            @endif
            @if (session()->has('success'))
              <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
                {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            @endif
            @component('cliente.form_create_edit', ['cliente' => $cliente])
            @endcomponent
        </div>
    </div>
</div>
@endsection

resources/views/cliente/form_create_edit.blade.php
@if (isset($cliente->id))
<form method="post" class action="{{ route('clientes.update', $cliente['id']) }}">
    @csrf
    @method('PUT')
    <input type="hidden" name="cliente_id" value="{{$cliente->id}}" />
@else
<form method="post" action="{{ route('clientes.store') }}">
    @csrf
@endif
    <div class="form-group mb-3">
        <input type="text" class="form-control" value="{{ $cliente->nome_cliente ?? old('nome_cliente') }}" id="nome_cliente" name="nome_cliente"
        placeholder="Nome do Cliente">
    </div>
    <div class="form-group mb-3">
        <input type="email" class="form-control" value="{{ $cliente->email ?? old('email') }}" id="email" name="email"
        placeholder="E-mail do Cliente">
    </div>
    <div class="form-group mb-3">
        <input type="number" class="form-control" value="{{ $cliente->cpf ?? old('cpf') }}" id="cpf" name="cpf"
        placeholder="CPF do Cliente">
    </div>
    <div class="form-group mt-3">
        <button type="submit" class="btn btn-primary">@if (isset($cliente->id)) Editar @else Cadastrar @endif Cliente </button>
    </div>
</form>

resources/views/cliente/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{$titulo}}</h1>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="col">
                <div class="mt-10">
                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
                        @foreach ($errors->all() as $erro)
                            <p>{{ $erro }}</p>
                        @endforeach
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    @if (session()->has('success'))
                        <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
                        {{ session('success') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    <table class="table table-sm table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">CLIENTE</th>
                                <th scope="col">E-MAIL</th>
                                <th scope="col">CPF</th>
                                <th scope="col">DATA DE CRIAÇÃO</th>
                                <th scope="col">DATA DE ATUALIZAÇÃO</th>
                                <th scope="col">
                                    <div class="form-group">
                                        <a href="{{route('clientes.create')}}" class="btn btn-primary btn-sm">Cadastrar Cliente</a>
                                    </div>
                                </th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($clientes as $cliente)
                                <tr>
                                    <th scope="row">{{$cliente['id']}}</th>
                                    <td>{{$cliente['nome_cliente']}}</td>
                                    <td>{{$cliente['email']}}</td>
                                    <td>{{$cliente['cpf']}}</td>
                                    <td>{{date('d/m/Y h:m:s', strtotime($cliente['created_at']))}}</td>
                                    <td>{{date('d/m/Y h:m:s', strtotime($cliente['updated_at']))}}</td>
                                    <td><a href="{{route('clientes.edit', $cliente['id'])}}" class="btn btn-warning btn-sm">Editar Cliente</a></td>
                                    <td>
                                        <button type="button" class="btn btn-danger btn-sm deletar" data-toggle="modal" data-id="{{$cliente['id']}}" data-name="{{$cliente['nome_cliente']}}" data-target="#modalDeletar">
                                            Deletar Cliente
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalDeletar" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h5 class="modal-title link-light" id="TituloModalCentralizado">Deletar Cliente</h5>
                    <button type="button btn-dark" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Tem certeza que você deseja deletar o Cliente <b></b>?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary close" data-dismiss="modal">Cancelar</button>
                    <form method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Deletar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('.deletar, .close').click(function () {
                $('#modalDeletar').modal('toggle');
                $('.modal-body b').html($(this).attr("data-name"));
                $('.modal-footer form').attr("action", "/clientes/" + $(this).attr("data-id") + "");
            });
        });
    </script>
</div>
@endsection